### PR TITLE
PyPI ready

### PR DESCRIPTION
**Pull request by knaperek**
Hi, I've done some slight polishing, included a license file and inserted an example (from bitcoin wiki: https://en.bitcoin.it/wiki/API_reference_%28JSON-RPC%29). Also, I've published it on PyPI for everyone to easily install.

### CODE REVIEW

**Comment by luke-jr** [comment]
Needs rebase

**Comment by justinguy** [comment]
@knaperek Could we please get PyPi package updated?

**Comment by jgarzik** [comment]
Manually merged.

**Comment by knaperek** [comment]
PyPI package updated.

**Pull request closed without merging**
